### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by zorgiepoo** [zorgiepoo/Komet#7]
I created the current icon probably under 5 minutes. I'm not a great artist and it could probably be improved. The idea of the current icon was to resemble some kind of comet but it may look like a fruit.

**Comment by doches** [comment]
How about some version of a more death-to-dinosaurs-style comet?

## Original:
![comet128](https://cloud.githubusercontent.com/assets/25926/24587216/6b4e4696-17aa-11e7-910e-bd6c55929a8f.png)

## iBooks style:
![circle128](https://cloud.githubusercontent.com/assets/25926/24587214/5d84389a-17aa-11e7-8dfe-668d6414a269.png)
