### ISSUE TITLE
Be even more opinionated

### ISSUE THREAD

**Issue by jelder** [zorgiepoo/Komet#9]
I love Komet! Thank you for writing it.

Wonder if you've encountered this article before: https://chris.beams.io/posts/git-commit/

I think it would be great if would Komet whines when the first line starts with a lower case letter, or ends with a period, or isn't written in the imperative form. A good commit message should complete the sentence, "If applied, this commit will..."

**Comment by doches** [comment]
Komet already strongly encourages rules 1, 2, and 6 (blank line after subject and line limits for subject and body). Enforcing (optionally!) rules 3 and 4 from your linked article would be straightforward, but I'm not sure how one would enforce the imperative grammatical form without pulling in a [_ton_ of NLP baggage](https://nlp.stanford.edu/software/lex-parser.shtml). And even then, it would be quite English-language specific.

I quite like the idea of adding a preference for enforcing capitalisation and no-ending-punctuation, though. +1 to that!

**Comment by zorgiepoo** [comment]
Delayed response, but here we go!

I agree with imperative form not being worthwhile to enforce. With capitalization, I think there can be frequent exceptions. Some may prefix their commit message with a particular component for example.

I think the period rule may be doable. If there is only a single period in the subject line, then either decide to highlight the period with a warning, or remove the period when the user hits return. If the subject is already exceeding the warning limit, nothing has to be done. A false positive I can think of is a subject like: "Fix messages that end with a ."

I like to push for better commit messages but at the same time I don't want to annoy users if they don't care much, or there are often exceptional cases.

**Comment by zorgiepoo** [comment]
I added a warning highlight over the period in `master`, if the subject line ends with a period. This is only active if the subject line limit is enabled. It's pretty subtle, and I think it's fine to have on for most languages..

**Comment by zorgiepoo** [comment]
After thinking about it more, I might revert this as it's somewhat opinionated and not something Komet would help a great deal for visual feedback (imperative mood / capitalization / period are easier for a human to reason about, but visualizing character limits on the other hand is not).

**Comment by zorgiepoo** [comment]
Closing this issue for now given the above discussion; if developers want to use capitalization and no periods for subject, they will, but I don't think Komet can make UX significantly better to developers that already do that.
